import { motion } from 'framer-motion'
import { ChevronDown, Sparkles } from 'lucide-react'
import { GeButton } from '../components/ge-button'
import { handleScrollToFormTarget } from '../../../lib/scroll-to-form-target'

/**
 * Hero displays the brand Málaga → Costa del Sol creative directly under the white navbar.
 *
 * - **Mobile** (max-width 639px): 9:16 `hero-sample-sunny-mercedes-03-mobile.webp` (+ PNG)
 * - **sm and up**: 2:1 `hero-sample-sunny-mercedes-03.webp` (+ PNG)
 *
 * Assets are generated by `scripts/rebuild-hero-sample-03.mjs`. Desktop raster is
 * full composition; **mobile** is a simplified layout (fewer elements, more air).
 */
export function GeHero() {
  return (
    <section
      className="relative isolate overflow-hidden bg-gs-dark"
      aria-labelledby="ge-hero-title"
      id="top"
    >
      {/* Spacer for the fixed navbar — matches sticky crest + slightly roomier
          mobile bar (py-2.5) so the hero art does not feel jammed under icons. */}
      <div
        aria-hidden="true"
        className="h-[150px] w-full bg-white max-sm:h-[152px] sm:h-[156px] md:h-[168px] lg:h-[130px] xl:h-[142px]"
      />

      {/* Mobile: fractionally taller frame than 9:16 eases vertical crowding in-view
          (object-cover crops sides slightly). sm+ keeps desktop 2:1. */}
      <div className="relative w-full max-sm:aspect-[9/17] sm:aspect-[2/1]">
        <picture className="absolute inset-0 block h-full w-full">
          <source
            type="image/webp"
            media="(max-width: 639px)"
            srcSet="/images/hero-sample-sunny-mercedes-03-mobile.webp"
          />
          <source type="image/webp" media="(min-width: 640px)" srcSet="/images/hero-sample-sunny-mercedes-03.webp" />
          <source media="(max-width: 639px)" srcSet="/images/hero-sample-sunny-mercedes-03-mobile.png" />
          <img
            src="/images/hero-sample-sunny-mercedes-03.png"
            alt="GolfSol Ireland — From plane to fairway. Meet-and-greet at Málaga, golf-bag friendly Mercedes transfers, tee times pre-booked. Irish and Spanish phone lines: +353 87 446 4766 and +34 641 81 53 66."
            className="h-full w-full select-none object-cover object-center"
            fetchPriority="high"
            decoding="async"
          />
        </picture>

        {/* Hidden semantic H1 for SEO + AA — the visible headline lives in
            the composed image as raster art. */}
        <h1 id="ge-hero-title" className="sr-only">
          From Plane to Fairway — GolfSol Ireland Málaga to Costa del Sol golf transfers
        </h1>

        {/* Live CTA — centred under portrait hero on mobile; right-aligned sm+ (desktop art). */}
        <div className="pointer-events-none absolute inset-0 z-30 max-sm:flex max-sm:justify-center max-sm:items-end max-sm:px-5 max-sm:pb-[20%] sm:block">
          <motion.div
            className="pointer-events-auto max-sm:mx-auto max-sm:w-[min(18.5rem,calc(100%-2.5rem))] max-sm:shrink-0 sm:absolute sm:right-[4.5%] sm:bottom-[13.5%] sm:mx-0 sm:w-[min(17rem,44vw)] md:right-[5%] md:bottom-[12.5%] lg:right-[5.5%]"
            initial={{ opacity: 0, y: 14 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.4, duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.98 }}
          >
            <GeButton
              href="/contact"
              variant="gs-gold"
              size="lg"
              className="relative w-full min-h-[50px] justify-center overflow-hidden !rounded-2xl !py-3 !text-[0.88rem] !tracking-[0.16em] shadow-[0_14px_42px_rgba(255,199,44,0.55)] ring-2 ring-white/35 ring-offset-2 ring-offset-transparent transition-[box-shadow,filter] duration-300 hover:shadow-[0_18px_52px_rgba(255,199,44,0.78)] hover:brightness-[1.03] sm:!min-h-[54px] sm:!px-8 sm:!text-[0.92rem]"
            >
              <Sparkles className="h-4 w-4 shrink-0 opacity-90 sm:h-[1.05rem] sm:w-[1.05rem]" aria-hidden />
              Book now
            </GeButton>
          </motion.div>
        </div>

        {/* Animated scroll-down chevron, anchored to the right edge so it
            doesn't collide with the phone number on portrait mobile. */}
        <motion.a
          href="#design-package"
          onClick={(event) => handleScrollToFormTarget(event, '#design-package')}
          aria-label="Scroll to next section"
          className="absolute bottom-4 right-4 z-20 inline-flex h-11 w-11 items-center justify-center rounded-full border-2 border-white/85 bg-gs-dark/55 text-white backdrop-blur-md transition-colors hover:border-gs-gold hover:bg-gs-dark/75 hover:text-gs-gold md:bottom-6 md:left-1/2 md:right-auto md:h-12 md:w-12 md:-translate-x-1/2"
          animate={{ y: [0, 6, 0] }}
          transition={{ duration: 2, ease: 'easeInOut', repeat: Infinity }}
        >
          <ChevronDown className="h-5 w-5" />
        </motion.a>
      </div>
    </section>
  )
}
