import type { ReactNode } from 'react'
import { motion } from 'framer-motion'
import { ChevronDown, Sparkles } from 'lucide-react'
import { GeButton } from '../components/ge-button'
import { handleScrollToFormTarget } from '../../../lib/scroll-to-form-target'

export type GeHeroVariant = 'marketing' | 'portal'

export interface GeHeroProps {
  readonly variant?: GeHeroVariant
  /** Portal: kicker pill, main headline, supporting copy (shown over image bottom). */
  readonly portalKicker?: string
  readonly portalTitle?: string
  readonly portalSubtitle?: string
  readonly portalAdornment?: ReactNode
  /** Portal: live-updating line (e.g. Dublin time). */
  readonly portalTimestamp?: string
}

/**
 * Hero displays the brand Málaga → Costa del Sol creative directly under the white navbar.
 *
 * - **Mobile** (max-width 639px): 9:16 `hero-sample-sunny-mercedes-03-mobile.webp` (+ PNG)
 * - **sm and up**: 2:1 `hero-sample-sunny-mercedes-03.webp` (+ PNG)
 *
 * Assets are generated by `scripts/rebuild-hero-sample-03.mjs`. Desktop raster is
 * full composition; **mobile** is a simplified layout (fewer elements, more air).
 */
export function GeHero({
  variant = 'marketing',
  portalKicker,
  portalTitle,
  portalSubtitle,
  portalAdornment,
  portalTimestamp
}: GeHeroProps = {}) {
  const isPortal = variant === 'portal'
  return (
    <section
      className="relative isolate overflow-hidden bg-gs-dark"
      aria-labelledby="ge-hero-title"
      id="top"
    >
      {/* Spacer for the fixed navbar — matches sticky crest + slightly roomier
          mobile bar (py-2.5) so the hero art does not feel jammed under icons. */}
      <div
        aria-hidden="true"
        className="h-[150px] w-full bg-white max-sm:h-[152px] sm:h-[156px] md:h-[168px] lg:h-[130px] xl:h-[142px]"
      />

      {/* Mobile: fractionally taller frame than 9:16 eases vertical crowding in-view
          (object-cover crops sides slightly). sm+ keeps desktop 2:1. */}
      <div className="relative w-full max-sm:aspect-[9/17] sm:aspect-[2/1]">
        <picture className="absolute inset-0 block h-full w-full">
          <source
            type="image/webp"
            media="(max-width: 639px)"
            srcSet="/images/hero-sample-sunny-mercedes-03-mobile.webp"
          />
          <source type="image/webp" media="(min-width: 640px)" srcSet="/images/hero-sample-sunny-mercedes-03.webp" />
          <source media="(max-width: 639px)" srcSet="/images/hero-sample-sunny-mercedes-03-mobile.png" />
          <img
            src="/images/hero-sample-sunny-mercedes-03.png"
            alt="GolfSol Ireland — From plane to fairway. Meet-and-greet at Málaga, golf-bag friendly Mercedes transfers, tee times pre-booked. Irish and Spanish phone lines: +353 87 446 4766 and +34 641 81 53 66."
            className="h-full w-full select-none object-cover object-center"
            fetchPriority="high"
            decoding="async"
          />
        </picture>

        {/* Marketing: headline is in raster; sr-only for SEO. Portal H1 lives in overlay below. */}
        {!isPortal ? (
          <h1 id="ge-hero-title" className="sr-only">
            From Plane to Fairway — GolfSol Ireland Málaga to Costa del Sol golf transfers
          </h1>
        ) : null}

        {isPortal && (portalTitle || portalKicker || portalSubtitle || portalTimestamp) ? (
          <div className="pointer-events-none absolute inset-0 z-30 flex flex-col justify-end bg-gradient-to-t from-gs-dark/95 via-gs-dark/55 to-transparent pb-[12%] pt-32 max-sm:pb-[18%] sm:pb-[10%]">
            <div className="pointer-events-auto mx-auto w-full max-w-[1180px] px-5 sm:px-8">
              <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
                <div className="min-w-0">
                  {portalKicker ? (
                    <p className="inline-flex rounded-full border border-gs-gold/40 bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-[0.22em] text-gs-gold shadow-sm backdrop-blur">
                      {portalKicker}
                    </p>
                  ) : null}
                  {portalTitle ? (
                    <h1
                      id="ge-hero-title"
                      className="mt-4 max-w-3xl text-[2rem] font-extrabold leading-[1.06] tracking-[-0.02em] text-white [text-shadow:0_2px_22px_rgba(0,0,0,0.5)] sm:text-[2.65rem] md:text-[3rem]"
                    >
                      {portalTitle}
                    </h1>
                  ) : null}
                  {portalTimestamp ? (
                    <p className="mt-3 text-sm font-semibold text-emerald-100/95 [text-shadow:0_1px_14px_rgba(0,0,0,0.45)] md:text-base">
                      {portalTimestamp}
                    </p>
                  ) : null}
                  {portalSubtitle ? (
                    <p className="mt-4 max-w-2xl text-sm leading-relaxed text-emerald-50/95 [text-shadow:0_1px_14px_rgba(0,0,0,0.4)] md:text-[1.02rem] md:leading-8">
                      {portalSubtitle}
                    </p>
                  ) : null}
                </div>
                {portalAdornment ? <div className="shrink-0">{portalAdornment}</div> : null}
              </div>
            </div>
          </div>
        ) : null}

        {!isPortal ? (
          <>
            {/* Live CTA — centred under portrait hero on mobile; right-aligned sm+ (desktop art). */}
            <div className="pointer-events-none absolute inset-0 z-30 max-sm:flex max-sm:justify-center max-sm:items-end max-sm:px-5 max-sm:pb-[20%] sm:block">
              <motion.div
                className="pointer-events-auto max-sm:mx-auto max-sm:w-[min(18.5rem,calc(100%-2.5rem))] max-sm:shrink-0 sm:absolute sm:right-[4.5%] sm:bottom-[13.5%] sm:mx-0 sm:w-[min(17rem,44vw)] md:right-[5%] md:bottom-[12.5%] lg:right-[5.5%]"
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4, duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.98 }}
              >
                <GeButton
                  href="/contact"
                  variant="gs-gold"
                  size="lg"
                  className="relative w-full min-h-[50px] justify-center overflow-hidden !rounded-2xl !py-3 !text-[0.88rem] !tracking-[0.16em] shadow-[0_14px_42px_rgba(255,199,44,0.55)] ring-2 ring-white/35 ring-offset-2 ring-offset-transparent transition-[box-shadow,filter] duration-300 hover:shadow-[0_18px_52px_rgba(255,199,44,0.78)] hover:brightness-[1.03] sm:!min-h-[54px] sm:!px-8 sm:!text-[0.92rem]"
                >
                  <Sparkles className="h-4 w-4 shrink-0 opacity-90 sm:h-[1.05rem] sm:w-[1.05rem]" aria-hidden />
                  Book now
                </GeButton>
              </motion.div>
            </div>

            <motion.a
              href="#design-package"
              onClick={(event) => handleScrollToFormTarget(event, '#design-package')}
              aria-label="Scroll to next section"
              className="absolute bottom-4 right-4 z-20 inline-flex h-11 w-11 items-center justify-center rounded-full border-2 border-white/85 bg-gs-dark/55 text-white backdrop-blur-md transition-colors hover:border-gs-gold hover:bg-gs-dark/75 hover:text-gs-gold md:bottom-6 md:left-1/2 md:right-auto md:h-12 md:w-12 md:-translate-x-1/2"
              animate={{ y: [0, 6, 0] }}
              transition={{ duration: 2, ease: 'easeInOut', repeat: Infinity }}
            >
              <ChevronDown className="h-5 w-5" />
            </motion.a>
          </>
        ) : null}
      </div>
    </section>
  )
}
