import type { ReactNode } from 'react'
import { m  } from 'framer-motion'
import { ChevronDown, Sparkles } from 'lucide-react'
import {
  BRAND_ADMIN_OPERATIONS_HERO_ALT,
  BRAND_CLIENT_PORTAL_HERO_ILLUSTRATION_ALT,
  BRAND_CLIENT_PORTAL_HERO_ILLUSTRATION_SRC,
  BRAND_FLEET_HERO_IMAGE_SRC,
  BRAND_PORTAL_HERO_GOLF_BACKDROP_SRC
} from '../../../lib/brand-visual-assets'

/** Same resolution as `AdminOperationsHubHero` — respects Vite `base`. */
const ADMIN_PORTAL_HERO_IMG_SRC = `${import.meta.env.BASE_URL}images/admin-operations-hero.png`
import { GeButton } from '../components/ge-button'
import { handleScrollToFormTarget } from '../../../lib/scroll-to-form-target'

export type GeHeroVariant = 'marketing' | 'portal'

export interface GeHeroProps {
  readonly variant?: GeHeroVariant
  /** Portal: kicker pill, main headline, supporting copy (shown over image bottom). */
  readonly portalKicker?: string
  readonly portalTitle?: string
  readonly portalSubtitle?: string
  readonly portalAdornment?: ReactNode
  /** Portal: live-updating line (e.g. Dublin time). */
  readonly portalTimestamp?: string
  /** Client: bespoke illustration. Admin: operations hero. Driver: twilight + fleet (`classic`). */
  readonly portalBackdrop?: 'client' | 'admin' | 'classic'
}

/**
 * Hero displays the brand Málaga → Costa del Sol creative directly under the white navbar.
 *
 * - **Mobile** (max-width 639px): 9:16 `hero-sample-sunny-mercedes-03-mobile.webp` (+ PNG)
 * - **sm and up**: 2:1 `hero-sample-sunny-mercedes-03.webp` (+ PNG)
 *
 * Assets are generated by `scripts/rebuild-hero-sample-03.mjs` (desktop ~1920×960,
 * mobile ~1296×2304 WebP/PNG). Desktop raster is the full composition; **mobile** is a
 * simplified layout (fewer elements, more air).
 */
export function GeHero({
  variant = 'marketing',
  portalKicker,
  portalTitle,
  portalSubtitle,
  portalAdornment,
  portalTimestamp,
  portalBackdrop = 'classic'
}: GeHeroProps = {}) {
  const isPortal = variant === 'portal'
  return (
    <section
      className="relative isolate overflow-hidden bg-gs-dark"
      aria-labelledby="ge-hero-title"
      id="top"
    >
      {/* Spacer for the fixed navbar — matches sticky crest + slightly roomier
          mobile bar (py-2.5) so the hero art does not feel jammed under icons. */}
      <div
        aria-hidden="true"
        className="h-[150px] w-full bg-white max-sm:h-[152px] sm:h-[156px] md:h-[168px] lg:h-[130px] xl:h-[142px]"
      />

      {/* Mobile: fractionally taller frame than 9:16 eases vertical crowding in-view
          (object-cover crops sides slightly). sm+ keeps desktop 2:1. */}
      <div className="relative w-full max-sm:aspect-[9/17] sm:aspect-[2/1]">
        {isPortal && portalBackdrop === 'client' ? (
          <div className="absolute inset-0 z-0">
            <img
              alt={BRAND_CLIENT_PORTAL_HERO_ILLUSTRATION_ALT}
              className="h-full w-full scale-[1.02] object-cover object-[center_42%] sm:object-[center_38%]"
              decoding="async"
              fetchPriority="high"
              src={BRAND_CLIENT_PORTAL_HERO_ILLUSTRATION_SRC}
            />
            <div
              aria-hidden
              className="absolute inset-0 bg-gradient-to-br from-gs-dark/88 via-emerald-950/55 to-[#0a1f14]/70"
            />
            <div
              aria-hidden
              className="absolute inset-0 bg-[radial-gradient(ellipse_120%_80%_at_70%_20%,rgba(213,198,0,0.12),transparent_55%)]"
            />
            <div aria-hidden className="absolute inset-0 bg-gradient-to-t from-black/[0.93] via-gs-dark/50 to-transparent" />
            <div
              aria-hidden
              className="absolute inset-0 opacity-[0.35] mix-blend-overlay"
              style={{
                backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.05'/%3E%3C/svg%3E")`
              }}
            />
          </div>
        ) : isPortal && portalBackdrop === 'admin' ? (
          <div className="absolute inset-0 z-0">
            <img
              alt={BRAND_ADMIN_OPERATIONS_HERO_ALT}
              className="h-full w-full object-cover object-[center_45%] sm:object-[center_40%]"
              decoding="async"
              fetchPriority="high"
              src={ADMIN_PORTAL_HERO_IMG_SRC}
            />
            <div
              aria-hidden
              className="absolute inset-0 bg-gradient-to-br from-gs-dark/85 via-emerald-950/50 to-[#0a1f14]/68"
            />
            <div
              aria-hidden
              className="absolute inset-0 bg-[radial-gradient(ellipse_120%_80%_at_72%_18%,rgba(213,198,0,0.1),transparent_55%)]"
            />
            <div aria-hidden className="absolute inset-0 bg-gradient-to-t from-black/[0.92] via-gs-dark/48 to-transparent" />
            <div
              aria-hidden
              className="absolute inset-0 opacity-[0.3] mix-blend-overlay"
              style={{
                backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 256 256' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.05'/%3E%3C/svg%3E")`
              }}
            />
          </div>
        ) : isPortal ? (
          <>
            <div className="absolute inset-0 z-0">
              <img
                alt=""
                className="h-full w-full object-cover object-center"
                decoding="async"
                fetchPriority="high"
                src={BRAND_PORTAL_HERO_GOLF_BACKDROP_SRC}
              />
              <div
                aria-hidden
                className="absolute inset-0 bg-gradient-to-br from-gs-dark/82 via-forest-950/40 to-emerald-950/30"
              />
              <div aria-hidden className="absolute inset-0 bg-gradient-to-t from-black/90 via-gs-dark/45 to-gs-dark/20" />
            </div>
            <img
              alt=""
              aria-hidden
              className="pointer-events-none absolute bottom-0 left-1/2 z-[1] max-h-[min(46vh,380px)] w-auto max-w-[min(96%,520px)] -translate-x-1/2 object-contain object-bottom opacity-[0.97] drop-shadow-[0_28px_80px_rgba(0,0,0,0.6)] sm:left-auto sm:right-[4%] sm:max-h-[min(52vh,460px)] sm:translate-x-0 md:right-[6%]"
              decoding="async"
              src={BRAND_FLEET_HERO_IMAGE_SRC}
            />
          </>
        ) : (
          <picture className="absolute inset-0 block h-full w-full">
            <source
              type="image/webp"
              media="(max-width: 639px)"
              srcSet="/images/hero-sample-sunny-mercedes-03-mobile.webp 1080w"
              sizes="100vw"
            />
            <source
              type="image/webp"
              media="(min-width: 640px)"
              srcSet="/images/hero-sample-sunny-mercedes-03.webp 1600w"
              sizes="100vw"
            />
            <source
              media="(max-width: 639px)"
              srcSet="/images/hero-sample-sunny-mercedes-03-mobile.png 1080w"
              sizes="100vw"
            />
            <img
              src="/images/hero-sample-sunny-mercedes-03.png"
              alt="GolfSol Ireland — From plane to fairway. Meet-and-greet at Málaga, golf-bag friendly Mercedes transfers, tee times pre-booked. Irish and Spanish phone lines: +353 87 446 4766 and +34 641 81 53 66."
              className="h-full w-full select-none object-cover object-center"
              width={1600}
              height={800}
              sizes="100vw"
              fetchPriority="high"
              decoding="async"
            />
          </picture>
        )}

        {/* Marketing: headline is in raster; sr-only for SEO. Portal H1 lives in overlay below. */}
        {!isPortal ? (
          <h1 id="ge-hero-title" className="sr-only">
            From Plane to Fairway — GolfSol Ireland Málaga to Costa del Sol golf transfers
          </h1>
        ) : null}

        {isPortal && (portalTitle || portalKicker || portalSubtitle || portalTimestamp) ? (
          <div className="pointer-events-none absolute inset-0 z-30 flex flex-col justify-end bg-gradient-to-t from-black/92 via-gs-dark/50 to-transparent pb-[12%] pt-32 max-sm:pb-[18%] sm:pb-[10%]">
            <div className="pointer-events-auto mx-auto w-full max-w-[1180px] px-5 sm:px-8">
              <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between">
                <div className="min-w-0">
                  {portalKicker ? (
                    <m.p
                      className="inline-flex rounded-full border border-gs-gold/50 bg-gradient-to-r from-white/[0.14] to-white/[0.06] px-3.5 py-1.5 text-xs font-extrabold uppercase tracking-[0.22em] text-gs-gold shadow-[0_0_24px_rgba(213,198,0,0.15)] backdrop-blur-md sm:text-sm"
                      initial={{ opacity: 0, y: 8 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
                    >
                      {portalKicker}
                    </m.p>
                  ) : null}
                  {portalTitle ? (
                    <m.h1
                      id="ge-hero-title"
                      className="mt-4 max-w-3xl text-[2.25rem] font-extrabold leading-[1.06] tracking-[-0.02em] text-white [text-shadow:0_2px_28px_rgba(0,0,0,0.55),0_0_40px_rgba(16,185,129,0.12)] sm:text-[2.95rem] md:text-[3.35rem]"
                      initial={{ opacity: 0, y: 12 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.06, duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
                    >
                      {portalTitle}
                    </m.h1>
                  ) : null}
                  {portalTimestamp ? (
                    <m.div
                      className="mt-3 flex flex-wrap items-baseline gap-x-2 gap-y-1"
                      initial={{ opacity: 0 }}
                      animate={{ opacity: 1 }}
                      transition={{ delay: 0.12, duration: 0.4 }}
                    >
                      <p className="text-base font-semibold tabular-nums text-white [text-shadow:0_1px_16px_rgba(0,0,0,0.5)] md:text-lg">
                        {portalTimestamp}
                      </p>
                      <span className="text-xs font-bold uppercase tracking-[0.16em] text-white md:text-sm">
                        Ireland (Dublin)
                      </span>
                    </m.div>
                  ) : null}
                  {portalSubtitle ? (
                    <m.p
                      className="mt-4 max-w-2xl border-l-2 border-gs-gold/50 pl-4 text-base leading-relaxed text-emerald-50/[0.96] [text-shadow:0_1px_14px_rgba(0,0,0,0.45)] md:text-lg md:leading-8"
                      initial={{ opacity: 0, y: 6 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.18, duration: 0.45, ease: [0.22, 1, 0.36, 1] }}
                    >
                      {portalSubtitle}
                    </m.p>
                  ) : null}
                </div>
                {portalAdornment ? <div className="shrink-0">{portalAdornment}</div> : null}
              </div>
            </div>
          </div>
        ) : null}

        {!isPortal ? (
          <>
            {/* Live CTA — centred under portrait hero on mobile; right-aligned sm+ (desktop art). */}
            <div className="pointer-events-none absolute inset-0 z-30 max-sm:flex max-sm:justify-center max-sm:items-end max-sm:px-5 max-sm:pb-[20%] sm:block">
              <m.div
                className="pointer-events-auto max-sm:mx-auto max-sm:w-[min(18.5rem,calc(100%-2.5rem))] max-sm:shrink-0 sm:absolute sm:right-[4.5%] sm:bottom-[13.5%] sm:mx-0 sm:w-[min(17rem,44vw)] md:right-[5%] md:bottom-[12.5%] lg:right-[5.5%]"
                initial={{ opacity: 0, y: 14 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 0.4, duration: 0.55, ease: [0.22, 1, 0.36, 1] }}
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.98 }}
              >
                <GeButton
                  href="/contact"
                  variant="gs-gold"
                  size="lg"
                  className="relative w-full min-h-[50px] justify-center overflow-hidden !rounded-2xl !py-3 !text-[0.88rem] !tracking-[0.16em] shadow-[0_14px_42px_rgba(213,198,0,0.55)] ring-2 ring-white/35 ring-offset-2 ring-offset-transparent transition-[box-shadow,filter] duration-300 hover:shadow-[0_18px_52px_rgba(213,198,0,0.78)] hover:brightness-[1.03] sm:!min-h-[54px] sm:!px-8 sm:!text-[0.92rem]"
                >
                  <Sparkles className="h-4 w-4 shrink-0 opacity-90 sm:h-[1.05rem] sm:w-[1.05rem]" aria-hidden />
                  Book now
                </GeButton>
              </m.div>
            </div>

            <m.a
              href="#design-package"
              onClick={(event) => handleScrollToFormTarget(event, '#design-package')}
              aria-label="Scroll to next section"
              className="absolute bottom-4 right-4 z-20 inline-flex h-11 w-11 items-center justify-center rounded-full border-2 border-white/85 bg-gs-dark/55 text-white backdrop-blur-md transition-colors hover:border-gs-gold hover:bg-gs-dark/75 hover:text-gs-gold md:bottom-6 md:left-1/2 md:right-auto md:h-12 md:w-12 md:-translate-x-1/2"
              animate={{ y: [0, 6, 0] }}
              transition={{ duration: 2, ease: 'easeInOut', repeat: Infinity }}
            >
              <ChevronDown className="h-5 w-5" />
            </m.a>
          </>
        ) : null}
      </div>
    </section>
  )
}
